name: 'Create Terraform provider file for GCP'
description: 'Creates a .tf file for Terraform provider configuration for GCP'
inputs:
  region:
    description: 'GCP region'
    required: true
  project:
    description: 'GCP project'
    required: true

runs:
  using: node20
  main: dist/index.js
