name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          project: "project1"
          region: "eu-west3"

      - name: print file
        run: cat provider.tf
